stages:
  # - ansible-lint
  - deploy_app

# ansible-lint:
#   only:
#       - master
#   stage: ansible-lint
#   image: yokogawa/ansible-lint
#   allow_failure: true
#   script:

  # - 'ansible-lint setup.yml'

deploy_app:
  only:
      - master
  stage: deploy_app
  # TODO: use ubuntu image to install and ansible image to exec ansible from another container in the same network
  image: ubuntu:latest
  # image: williamyeh/ansible:ubuntu18.04
  script:
      - apt update
      - apt install --yes software-properties-common
      - apt-add-repository --yes --update ppa:ansible/ansible
      - apt install --yes ansible
      - 'ansible-playbook -i gitlab-ci-inventory.ini setup.yml'
