image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git submodule update --init --recursive -- repos/imago
      podman-compose pull imago
      podman-compose run imago ecto.setup
    command: podman-compose up imago
  - init: |
      git submodule update --init --recursive -- repos/imago_front
      podman-compose pull imago_front
    command: podman-compose up imago_front
  - init: |
      podman-compose pull
      podman-compose run synapse generate
    command: podman-compose up

ports:
  - port: 9000
    onOpen: open-preview
  - port: 8008