version: '3'

services:
  imago:
    # build: ./repos/imago
    image: registry.gitlab.com/imago-project/imago:latest
    depends_on:
      - postgres_imago
      - synapse
    environment:
      - WAIT_HOSTS=postgres_imago:5432 #,gremlin:8182
      - WAIT_HOSTS_TIMEOUT=60

  imago_front:
    # build: ./repos/imago_front
    image: registry.gitlab.com/imago-project/imago_front:latest

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.12.4-py3
    restart: unless-stopped

  postgres_imago:
    image: postgres:12.0-alpine
    domainname: postgres_imago

  wdqs:
    image: wikibase/wdqs:0.3.10
    command: /runBlazegraph.sh
