version: '3'

volumes:
  imago_deps:
  imago_node_deps:
  imago_build_files:

  synapse_data:
  synapse_media_store:

  wdqs_data:

services:
  imago:
    # ports:
    #   - "4000:4000"
    volumes:
      - ./repos/imago:/opt/app:rw
      - imago_deps:/opt/app/deps
      - imago_node_deps:/opt/app/assets/node_modules
      - imago_build_files:/opt/app/_build
    environment:
      - MIX_ENV=prod
      - POSTGRES_HOST=postgres_imago
      - POSTGRES_USER=imago
      - POSTGRES_PASSWORD=postgres
    labels:
      - traefik.http.routers.api.entryPoints=http
      - traefik.http.routers.api.rule=Path(`/api`)
      # - traefik.docker.network=traefik_default

  imago_front:
    build:
      context: ./repos/imago_front
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - MATRIX_URL="matrix.alpha.imago.pm"
      - API_URL="alpha.imago.pm/api"
    expose:
      - 80
    # command: "npm run server-tls"
    # ports:
    #   - "9000:9000"
    labels:
      - traefik.http.routers.front.entryPoints=http
      - traefik.http.routers.front.rule=Path(`/`)
      - traefik.http.services.front.loadbalancer.server.port=80
      # - traefik.docker.network=traefik_default

  synapse:
    # command:  migrate_config
    # command:  generate
    environment:
      - SYNAPSE_SERVER_NAME=alpha.imago.pm
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      # - SYNAPSE_LOG_LEVEL=INFO
      # - SYNAPSE_LOG_LEVEL=DEBUG
      # - POSTGRES_HOST=postgres_synapse
      # - POSTGRES_USER=synapse
      # - POSTGRES_PASSWORD=postgres
    volumes:
      # You may either store all the files in a local folder
      # - ./synapse-files:/data
      - synapse_data:/data
      - synapse_media_store:/data/media_store
      - ./synapse-homeserver.yaml:/data/homeserver.yaml
      - ./synapse-imago.yaml:/data/appservices/imago.yaml
      # - ./synapse-signing.key:/data/matrix.imago.local.signing.key
      # - ./synapse-log.config:/data/matrix.imago.local.log.config
      # - ./repos/imago/imago.yaml:/data/appservices/imago.yaml
      # .. or you may split this between different storage points
      # - ./files:/data
      # - /path/to/ssd:/data/uploads
      # - /path/to/large_hdd:/data/media
    # depends_on:
    #   - postgres_synapse
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    # ports:
    #   - 8008:8008/tcp
    #   - 8448:8448/tcp
    # ... or use a reverse proxy, here is an example for traefik:
    labels:
      - traefik.http.routers.synapse.entryPoints=matrix
      - traefik.http.routers.synapse.rule=Host(`matrix.alpha.imago.pm`)
      # - traefik.docker.network=traefik_default
    #   - traefik.enable=true
    #   - traefik.frontend.rule=Host:my.matrix.Host
    #   - traefik.port=8008
      - traefik.enable=true
      - traefik.http.routers.http-synapse.entryPoints=http
      - traefik.http.routers.http-synapse.rule=Host(`matrix.alpha.imago.pm`)
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-synapse.middlewares=https_redirect
      - traefik.http.routers.https-synapse.entryPoints=https
      - traefik.http.routers.https-synapse.rule=Host(`matrix.alpha.imago.pm`)
      - traefik.http.routers.https-synapse.service=synapse
      - traefik.http.routers.https-synapse.tls=true
      - traefik.http.services.synapse.loadbalancer.server.port=8008
      - traefik.http.routers.https-synapse.tls.certResolver=le-ssl

  postgres_imago:
    environment:
      - POSTGRES_USER=imago
    # Change that password, of course!
      - POSTGRES_PASSWORD=postgres
    volumes:
      # You may store the database tables in a local folder..
      - ./data/imago:/var/lib/postgresql/data
      # .. or store them on some high performance storage for better results
      # - /path/to/ssd/storage:/var/lib/postgresql/data

  wdqs:
    volumes:
      - wdqs_data:/wdqs/data
    environment:
      - WIKIBASE_HOST=www.wikidata.org
      - WDQS_HOST=wdqs
      - WDQS_PORT=9999

  traefik:
    image: traefik:v2.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
        # - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.matrix.address=:8448"
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
