version: '3'

volumes:
  imago_front_deps:
  imago_front_compilation_items:

  imago_deps:
  imago_node_deps:
  imago_build_files:

  synapse_data:
  synapse_media_store:

  wdqs_data:

services:
  imago:
    hostname: api.imago.local
    # ports:
    #   - "4000:4000"
    volumes:
      - ./repos/imago:/opt/app:rw
      - imago_deps:/opt/app/deps
      - imago_node_deps:/opt/app/assets/node_modules
      - imago_build_files:/opt/app/_build
    environment:
      - MIX_ENV=dev
      - POSTGRES_HOST=postgres_imago
      - POSTGRES_USER=imago
      - POSTGRES_PASSWORD=postgres
    labels:
      - traefik.http.routers.api.entryPoints=api
      - traefik.http.routers.api.rule=Host(`api.imago.local`)
      # - traefik.docker.network=traefik_default

  imago_front:
    hostname: app.imago.local
    environment:
      - NODE_ENV=development
      - MATRIX_URL="matrix.imago.local:8448"
      - API_URL="api.imago.local:4000"
    volumes:
      - ./repos/imago_front:/home/node/app:rw
      - imago_front_deps:/home/node/app/node_modules
      - imago_front_compilation_items:/home/node/app/lib
      - /dev/null:/home/node/app/.merlin
    expose:
      - "9000"
    # command: "npm run server-tls"
    # ports:
    #   - "9000:9000"
    labels:
      - traefik.http.routers.front.entryPoints=front
      - traefik.http.routers.front.rule=Host(`app.imago.local`)
      - traefik.http.services.front.loadbalancer.server.port=9000
      # - traefik.docker.network=traefik_default

  synapse:
    hostname: matrix.imago.local
    # command:  migrate_config
    # command:  generate
    environment:
      - SYNAPSE_SERVER_NAME=matrix.imago.local
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=ERROR
      # - SYNAPSE_LOG_LEVEL=INFO
      # - SYNAPSE_LOG_LEVEL=DEBUG
      # - POSTGRES_HOST=postgres_synapse
      # - POSTGRES_USER=synapse
      # - POSTGRES_PASSWORD=postgres
    volumes:
      # You may either store all the files in a local folder
      # - ./synapse-files:/data
      - synapse_data:/data
      - synapse_media_store:/data/media_store
      - ./synapse-homeserver.yaml:/data/homeserver.yaml
      - ./synapse-imago.yaml:/data/appservices/imago.yaml
      # - ./synapse-signing.key:/data/matrix.imago.local.signing.key
      # - ./synapse-log.config:/data/matrix.imago.local.log.config
      # - ./repos/imago/imago.yaml:/data/appservices/imago.yaml
      # .. or you may split this between different storage points
      # - ./files:/data
      # - /path/to/ssd:/data/uploads
      # - /path/to/large_hdd:/data/media
    # depends_on:
    #   - postgres_synapse
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    # ports:
    #   - 8008:8008/tcp
    #   - 8448:8448/tcp
    # ... or use a reverse proxy, here is an example for traefik:
    labels:
      - traefik.http.routers.synapse.entryPoints=synapse
      - traefik.http.routers.synapse.rule=Host(`matrix.imago.local`)
      # - traefik.docker.network=traefik_default
    #   - traefik.enable=true
    #   - traefik.frontend.rule=Host:my.matrix.Host
    #   - traefik.port=8008

  postgres_imago:
    environment:
      - POSTGRES_USER=imago
    # Change that password, of course!
      - POSTGRES_PASSWORD=postgres
    volumes:
      # You may store the database tables in a local folder..
      - ./data/imago:/var/lib/postgresql/data
      # .. or store them on some high performance storage for better results
      # - /path/to/ssd/storage:/var/lib/postgresql/data

  wdqs:
    hostname: wdqs.imago.local
    volumes:
      - wdqs_data:/wdqs/data
    environment:
      - WIKIBASE_HOST=www.wikidata.org
      - WDQS_HOST=wdqs.imago.local
      - WDQS_PORT=9999
