---
- hosts: front
# TODO: make it run not w/ root!!
# + add TLS and imago-dev.img.tls.crt and imago-dev.img.tls.key
  vars:
    front_user: front
    front_path: /home/front/imago_front
    front_cmd: /usr/bin/npm run server
  remote_user: "{{ front_user }}"
  handlers:
    - name: "reload systemd"
      systemd:
        daemon_reload: yes
      listen: "reload systemd"
      when: docker_enabled is not defined


    - name: "restart front"
      service:
        name: "front"
        state: restarted
        enabled: yes
      listen: "restart front"
      when: docker_enabled is not defined
    
  tasks:
    - user:
        name: "{{ front_user }}"
      become: yes

    - git:
        repo: "https://gitlab.com/imago-project/imago_front"
        dest: "{{ front_path }}"
        force: yes
        # update: yes

    - apt:
        name: npm
        state: present 

  # sudo echo "127.0.0.1 {{  }}" >> /etc/hosts
  # npm run server-tls
    - name: install server
      npm:
        path: "{{ front_path }}"
        state: present
        production: no
        
    - name: Copy webpack config file
      template:
        src: "webpack.config.front.js.j2"
        dest: "{{ front_path }}/webpack.config.js"
      notify:
        - "restart front"

    - name: Deploy service file # RUN AS ROOT FOR DEBUG!!!
      template:
        src: "front.service.j2"
        dest: "/etc/systemd/system/front.service"
      notify:
        - "reload systemd"
        - "restart front"
      when: docker_enabled is not defined


    - name: run service front
      service:
        enabled: yes
        state: restarted
        name: front
      when: docker_enabled is not defined


    - name: run front server not as service
      shell: "/usr/bin/npm run server &"
      become: yes # TODO: make it run not w/ root!!
      args:
        chdir: "{{ front_path }}"
      when: docker_enabled
        # failed_when: "'already' not in 

