- hosts: postgresql
  tasks:
  - pip:
      name: psycopg2
      state: present # not required. choices: absent;forcereinstall;latest;present. The state of module,The 'forcereinstall' option is only available in Ansible 2.1 and above.
  roles:
    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: "{{ dbname }}"
      postgresql_users:
        - name: "{{ dbuser }}"
          password: "{{ dbpw }}"
      postgresql_global_config_options:
        - option: listen_addresses
          value: "*"