---
- hosts: all
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes


- hosts:
  - postgresql
  - synapse
  # vars:
    # pip_package: python3-pip

  roles:
  - geerlingguy.pip
  

- import_playbook: postgres.yml
# todo: create synapse user
- import_playbook: synapse.yml
- import_playbook: phoenix.yml
# todo: make it run by user
- import_playbook: front.yml