---
- hosts: synapse
# todo: create user for synapse
  vars:
    matrix_server_name: imago-dev
    matrix_synapse_deployment_method: pip
    matrix_synapse_baseurl: "https://{{ matrix_server_name }}"
    matrix_synapse_signing_key_path: "{{ matrix_synapse_base_path }}/tls/{{ matrix_server_name }}.signing.key"
    # matrix_synapse_version: "v1.3.1"

    matrix_synapse_pg_host: localhost
    matrix_synapse_pg_user: "{{ synapse_dbuser }}"
    matrix_synapse_pg_pass: "{{ synapse_dbpw }}"
    matrix_synapse_pg_db: "{{ synapse_dbname }}"
    matrix_synapse_report_stats: false # Report stats to matrix.org?
    
    # matrix_synapse_extra_config: # This disables port 8448
      # no_tls: true 

  # pre_tasks:
  # tasks:
  roles:
    - synapse