# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimSuffix `-imago-deploy` (trimPrefix `/` .Name) }}.pierre.local`)"

# API and dashboard configuration
api:
  insecure: true

accessLog: {}

entryPoints:
  api:
    address: ":4000"
  synapse:
    address: ":8008"
  front:
    address: ":80"

