handlers:
  - name: "reload systemd"
    systemd:
      daemon_reload: yes
    listen: "reload systemd"
    when: not docker_enabled


  - name: "restart front"
    service:
      name: "front"
      state: restarted
      enabled: yes
    listen: "restart front"
    when: not docker_enabled