---
- hosts: prod
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
    become: yes
  vars:
    install_environment: prod

# todo: make it run by user
- import_playbook: imago-front-dev.yml

- import_playbook: postgres.yml
- import_playbook: back-cert.yml

# todo: create synapse user
- import_playbook: synapse.yml
- import_playbook: imago-dev.yml
- import_playbook: neo4j-gremlin.yml
