---
- hosts: all
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
    become: yes
  vars:
    install_environment: prod

# todo: make it run by user
- import_playbook: front.yml
- import_playbook: back.yml