---
- hosts: dev
  pre_tasks:

    - name: Disable IPv6
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
          net.ipv6.conf.lo.disable_ipv6 = 1
      # notify: reboot

    - name: apply ipv6 disable
      command: sysctl -p
      become: yes

    - name: check ipv6 state
      shell: cat /proc/sys/net/ipv6/conf/all/disable_ipv6
      register: command_result
      failed_when: "'1' not in command_result.stdout"

  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
    become: yes
  vars: 
    - install_environment: 'dev'

    

# todo: make it run by user
- import_playbook: front.yml
- import_playbook: back.yml
