---
- hosts: back
# todo: create user for synapse
  vars:
    # matrix_synapse_version: "v1.3.1"
  # localhosts causes certificate generation bugs
    # matrix_server_name: localhost
    # selfsigned: true
    matrix_server_name: imago-dev
    matrix_synapse_deployment_method: pip
    matrix_synapse_baseurl: "https://{{ matrix_server_name }}"
    matrix_synapse_signing_key_path: "{{ matrix_synapse_base_path }}/tls/{{ matrix_server_name }}.signing.key"
    # Test variables, doesn't seem to be working. Maybe a hostname problem


    matrix_synapse_pg_host: localhost
    matrix_synapse_pg_user: "{{ synapse_dbuser }}"
    matrix_synapse_pg_pass: "{{ synapse_dbpw }}"
    matrix_synapse_pg_db: "{{ synapse_dbname }}"
    matrix_synapse_report_stats: false # Report stats to matrix.org?
    
    matrix_synapse_extra_config: # no_tls:true disables port 8448
      no_tls: false